document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset='UTF-8'>");
document.writeln("<style>");
document.writeln("table{");
document.writeln("border-collapse: collapse;");
document.writeln("width: 100%;");
document.writeln("}");
document.writeln("th, td{");
document.writeln("text-align: left;");
document.writeln("padding: 8px;");
document.writeln("}");
document.writeln("tr:nth-child(even){");
document.writeln("background-color: #fafafa;");
document.writeln("}");
document.writeln("th{");
document.writeln("background-color: #7799AA;");
document.writeln("color: white;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table>");
document.writeln("<tr><th>玩家名称</th><th>本服游玩时长</th><th>爆头率</th><th>普通感染者击杀</th><th>特感击杀</th><th>witch击杀</th><th>坦克击杀</th><th>黑枪比</th><th>黑枪</th><th>被黑枪</th><th>完成战役</th><th>团灭</th></tr>");
document.writeln("<tr><td>zwb is goat</td><td>0.1小时</td><td>11.94%</td><td>67</td><td>3</td><td>0</td><td>0</td><td></td><td>0</td><td>0</td><td>0</td><td>0</td></tr>");
document.writeln("<tr><td>xcfy00</td><td>3.6小时</td><td>9.23%</td><td>2026</td><td>98</td><td>1</td><td>7</td><td>3.27</td><td>603</td><td>184</td><td>11</td><td>7</td></tr>");
document.writeln("<tr><td>a418teapot</td><td>3.7小时</td><td>15.83%</td><td>1768</td><td>128</td><td>3</td><td>4</td><td>1.19</td><td>119</td><td>100</td><td>10</td><td>6</td></tr>");
document.writeln("<tr><td>Onoe Serika</td><td>3.6小时</td><td>18.24%</td><td>2132</td><td>107</td><td>5</td><td>8</td><td>0.57</td><td>147</td><td>257</td><td>11</td><td>7</td></tr>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("</html>");
