document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset='UTF-8'>");
document.writeln("<style>");
document.writeln("table{");
document.writeln("border-collapse: collapse;");
document.writeln("width: 100%;");
document.writeln("}");
document.writeln("th, td{");
document.writeln("text-align: left;");
document.writeln("padding: 8px;");
document.writeln("}");
document.writeln("tr:nth-child(even){");
document.writeln("background-color: #fafafa;");
document.writeln("}");
document.writeln("th{");
document.writeln("background-color: #7799AA;");
document.writeln("color: white;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table>");
document.writeln("<tr><th>玩家名称</th><th>近战击杀</th><th>救活队友</th><th>倒地</th><th>死亡</th><th>砍舌</th><th>推开HUNTER</th><th>秒妹</th><th>打碎石头</th><th>吃饼</th><th>触发警报</th></tr>");
document.writeln("<tr><td>a418teapot</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("</html>");
