document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset='UTF-8'>");
document.writeln("<style>");
document.writeln("table{");
document.writeln("border-collapse: collapse;");
document.writeln("width: 100%;");
document.writeln("}");
document.writeln("th, td{");
document.writeln("text-align: left;");
document.writeln("padding: 8px;");
document.writeln("}");
document.writeln("tr:nth-child(even){");
document.writeln("background-color: #fafafa;");
document.writeln("}");
document.writeln("th{");
document.writeln("background-color: #7799AA;");
document.writeln("color: white;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table>");
document.writeln("<tr><th>玩家名称</th><th>近战击杀</th><th>制服队友</th><th>救活队友</th><th>倒地</th><th>死亡</th><th>秒妹</th><th>打碎石头</th><th>吃饼</th><th>触发警报</th></tr>");
document.writeln("<tr><td>zwb is goat</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>");
document.writeln("<tr><td>xcfy00</td><td>880</td><td>9</td><td>17</td><td>76</td><td>15</td><td>1</td><td>0</td><td>4</td><td>2</td></tr>");
document.writeln("<tr><td>暴龙战士</td><td>39</td><td>1</td><td>1</td><td>11</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>");
document.writeln("<tr><td>a418teapot</td><td>805</td><td>1</td><td>39</td><td>62</td><td>12</td><td>1</td><td>4</td><td>13</td><td>0</td></tr>");
document.writeln("<tr><td>2307969226</td><td>413</td><td>4</td><td>18</td><td>23</td><td>7</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>");
document.writeln("<tr><td>Onoe Serika</td><td>920</td><td>5</td><td>55</td><td>68</td><td>15</td><td>16</td><td>1</td><td>15</td><td>0</td></tr>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("</html>");
